spring:
  profiles:
    active: dev
  rabbitmq:
    username: admin
    password: 123
    host: localhost
    port: 5672
    virtual-host: tweetme_dev

server:
  port: 8181

messaging:
  modify-queue:
    name: modifyQueue
    durable: false
    routing-key: tweet.action.modify
  log-queue:
    name: logQueue
    durable: false
    routing-key: tweet.action.modify
  exchange:
    name: tweetExchange
    routing-key-pattern: tweet.action.#

