version: "3.1"
services:
  rabbit-home:
    image: rabbitmq:3-management
    hostname: "rabbitmq-home"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
      - RABBITMQ_DEFAULT_VHOST=tweetme_dev

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "tweetme"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "tweetme"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  postgres: