version: "3.1"
services:
  rabbit-home:
    image: rabbitmq:3-management
    hostname: "rabbitmq-home"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
      - RABBITMQ_DEFAULT_VHOST=tweetme_dev